# Generated by Django 4.1.2 on 2022-10-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_cliente_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='venta',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
